import {
  Sparkles,
  FlaskConical,
  Globe,
  Users,
  Landmark,
  Swords,
  Network,
  Rocket,
  Smartphone,
  Infinity as InfinityIcon
} from "lucide-react";
import type {
  RoadmapFilterOption,
  RoadmapPhase,
  RoadmapStatus
} from "@/types/roadmap";

export const roadmapStatusLabels: Record<RoadmapStatus, string> = {
  completed: "COMPLETED",
  current: "CURRENT",
  confirmed: "CONFIRMED",
  planned: "PLANNED",
  "coming-soon": "COMING SOON"
};

export const roadmapFilterOptions: RoadmapFilterOption[] = [
  { label: "ALL", value: "all" },
  { label: "COMPLETED", value: "completed" },
  { label: "CURRENT", value: "current" },
  { label: "CONFIRMED", value: "confirmed" },
  { label: "PLANNED", value: "planned" },
  { label: "COMING SOON", value: "coming-soon" }
];

export const roadmapPhases: RoadmapPhase[] = [
  {
    id: "phase-0",
    number: 0,
    title: "Demo & Waitlist",
    status: "current",
    narrative: "The idea becomes visible.",
    description:
      "The foundation of Echelon becomes visible. Explore the early concept, experience the first interactive demo, and join the community as the world begins to take shape.",
    icon: Sparkles,
    countLabel: "FOUNDATIONAL FEATURES",
    milestones: [
      { label: "Interactive Demo", highlight: true },
      { label: "Waitlist" },
      { label: "Echelon Website" },
      { label: "Core Game Vision" },
      { label: "Living World Concept" },
      { label: "Territory System Concept" },
      { label: "Resource System Concept" },
      { label: "Population System Concept" },
      { label: "Economy Concept" },
      { label: "Kingdom System Concept" },
      { label: "Diplomacy Concept" },
      { label: "Warfare Concept" },
      { label: "Player-Driven History Concept" },
      { label: "Documentation" },
      { label: "Tokenomics" },
      { label: "Community Hub" },
      { label: "Telegram Community" }
    ]
  },
  {
    id: "phase-1",
    number: 1,
    title: "Presale & Private Testnet",
    status: "confirmed",
    narrative: "Early users enter the private network.",
    description:
      "The first private stage of Echelon's playable network. Early participants begin testing the systems that will power the persistent world.",
    icon: FlaskConical,
    countLabel: "DEVELOPMENT MILESTONES",
    spotlight: {
      label: "5% ECH Airdrop for Private Testers",
      note: "5% of the total ECH supply is allocated for the confirmed private tester airdrop."
    },
    note: "Individual allocation amounts, eligibility criteria, claim dates, and distribution mechanics have not been determined.",
    milestones: [
      { label: "Presale" },
      { label: "Private Testnet" },
      { label: "Private Tester Program" },
      { label: "Confirmed 5% ECH Tester Airdrop", confirmed: true },
      { label: "Early Game Systems Testing" },
      { label: "Territory Testing" },
      { label: "Resource Systems Testing" },
      { label: "Population Systems Testing" },
      { label: "Economy Testing" },
      { label: "Infrastructure Testing" },
      { label: "Player Progression Testing" },
      { label: "Multiplayer Infrastructure" },
      { label: "Wallet Integration" },
      { label: "Blockchain Integration" },
      { label: "Arbitrum Testnet Integration" },
      { label: "Transaction Abstraction Research" },
      { label: "State Synchronization" },
      { label: "Backend Infrastructure" },
      { label: "Analytics & Monitoring" },
      { label: "Bug Reporting" },
      { label: "Feedback System" },
      { label: "Anti-Abuse Systems" },
      { label: "Early Balancing" },
      { label: "Security Testing" }
    ]
  },
  {
    id: "phase-2",
    number: 2,
    title: "The Core World",
    status: "planned",
    narrative: "The world begins to exist.",
    description:
      "The foundations of Echelon's living world become playable.",
    icon: Globe,
    countLabel: "ROADMAP TARGETS",
    note: "These are development targets, not completed features.",
    milestones: [
      { label: "Persistent World Foundation", highlight: true },
      { label: "Territory Ownership" },
      { label: "Territory Hierarchy" },
      { label: "Regions" },
      { label: "Population" },
      { label: "Resources" },
      { label: "Resource Extraction" },
      { label: "Resource Production" },
      { label: "Infrastructure" },
      { label: "Territory Development" },
      { label: "Construction Systems" },
      { label: "Player Identity" },
      { label: "Player Progression" },
      { label: "Titles" },
      { label: "Prestige" },
      { label: "Territory History" },
      { label: "Ownership History" },
      { label: "World State" },
      { label: "Strategic Map" },
      { label: "Map Interaction" },
      { label: "Geographic Data" },
      { label: "Territory Visualization" },
      { label: "Resource Visualization" },
      { label: "Population Visualization" },
      { label: "Core Server Architecture" },
      { label: "Persistent State Storage" },
      { label: "World Simulation" },
      { label: "Economic Simulation" },
      { label: "Save / Recovery Systems" }
    ]
  },
  {
    id: "phase-3",
    number: 3,
    title: "Persistent Multiplayer",
    status: "planned",
    narrative: "Players begin shaping it together.",
    description:
      "Echelon becomes a shared world where players interact, compete, cooperate, and leave permanent consequences.",
    icon: Users,
    countLabel: "ROADMAP TARGETS",
    note: "These are development targets, not completed features.",
    milestones: [
      { label: "Multiplayer World" },
      { label: "Player Presence" },
      { label: "Shared Territory State" },
      { label: "Real-Time / Near Real-Time World Updates" },
      { label: "Player Interaction" },
      { label: "Alliances" },
      { label: "Diplomacy" },
      { label: "Trade" },
      { label: "Territory Conflicts" },
      { label: "Border Changes" },
      { label: "Political Entities" },
      { label: "Kingdom Creation", highlight: true },
      { label: "Nation Creation" },
      { label: "Sovereignty" },
      { label: "Vassalage / Political Relationships" },
      { label: "Treaties" },
      { label: "Peace Agreements" },
      { label: "War States" },
      { label: "Player Communication Systems" },
      { label: "Notifications" },
      { label: "Events" },
      { label: "World Events" },
      { label: "Historical Records" },
      { label: "Persistent Player Actions" },
      { label: "Server Scaling" },
      { label: "Synchronization Improvements" },
      { label: "Anti-Cheat Systems" },
      { label: "Moderation Infrastructure" }
    ]
  },
  {
    id: "phase-4",
    number: 4,
    title: "Economy & Governance",
    status: "planned",
    narrative: "Economies and governments emerge.",
    description:
      "The world develops an interconnected player-driven economy and political systems.",
    icon: Landmark,
    countLabel: "ROADMAP TARGETS",
    note: "Player-created currencies are planned game functionality. Not every player will be able to create a currency immediately, and no financial returns are implied.",
    milestones: [
      { label: "Player-Driven Economy", highlight: true },
      { label: "Markets" },
      { label: "Trade Routes" },
      { label: "Supply & Demand" },
      { label: "Resource Pricing" },
      { label: "Production Chains" },
      { label: "Economic Development" },
      { label: "National Economies" },
      { label: "Treasury Systems" },
      { label: "Taxation Systems" },
      { label: "Infrastructure Costs" },
      { label: "Economic Power" },
      { label: "Economic Rankings" },
      { label: "Kingdom Economies" },
      { label: "Nation Economies" },
      { label: "Player-Created Currencies" },
      { label: "Currency Requirements" },
      { label: "Currency Utility" },
      { label: "Governance Systems" },
      { label: "Political Institutions" },
      { label: "Laws" },
      { label: "Policy Systems" },
      { label: "Stability" },
      { label: "Legitimacy" },
      { label: "Public Economy" },
      { label: "Economic Statistics" },
      { label: "Economic History" },
      { label: "Market Analytics" },
      { label: "Economic Balancing" },
      { label: "Abuse Prevention" }
    ]
  },
  {
    id: "phase-5",
    number: 5,
    title: "Strategy & Warfare",
    status: "planned",
    narrative: "Power becomes conflict.",
    description:
      "Political power becomes strategic power. Players compete for territory, resources, influence, and survival.",
    icon: Swords,
    countLabel: "ROADMAP TARGETS",
    note: "Exact combat mechanics are not described here and are subject to development.",
    milestones: [
      { label: "Military Systems" },
      { label: "Armies" },
      { label: "Military Units" },
      { label: "Recruitment" },
      { label: "Military Logistics" },
      { label: "Supply Systems" },
      { label: "Defense Systems" },
      { label: "Fortifications" },
      { label: "Strategic Infrastructure" },
      { label: "Warfare" },
      { label: "Sieges" },
      { label: "Territory Conquest", highlight: true },
      { label: "Border Conflicts" },
      { label: "War Objectives" },
      { label: "Peace Terms" },
      { label: "Military Alliances" },
      { label: "Defense Pacts" },
      { label: "Strategic Planning" },
      { label: "Intelligence Systems" },
      { label: "Military Technology" },
      { label: "Command Systems" },
      { label: "Strategic Resources" },
      { label: "War Economy" },
      { label: "Military Rankings" },
      { label: "Victory Conditions" },
      { label: "Historical Wars" },
      { label: "War Records" },
      { label: "Battle History" },
      { label: "Dynamic Borders" },
      { label: "Post-War Recovery" },
      { label: "Balance Systems" }
    ]
  },
  {
    id: "phase-6",
    number: 6,
    title: "Open World & Ecosystem",
    status: "planned",
    narrative: "The world becomes an ecosystem.",
    description:
      "Echelon expands into a deeper, more interconnected player-driven ecosystem.",
    icon: Network,
    countLabel: "ROADMAP TARGETS",
    note: "Blockchain-related systems in this phase are planned, designed, and subject to development.",
    milestones: [
      { label: "Expanded World" },
      { label: "Advanced Territory Systems" },
      { label: "Advanced Economy" },
      { label: "Advanced Diplomacy" },
      { label: "Advanced Warfare" },
      { label: "Global Trade" },
      { label: "International Markets" },
      { label: "Advanced Political Systems" },
      { label: "Historical Events" },
      { label: "Dynamic World Events" },
      { label: "Player Organizations", highlight: true },
      { label: "Factions" },
      { label: "Advanced Titles" },
      { label: "Prestige Systems" },
      { label: "Civilization Development" },
      { label: "Regional Power" },
      { label: "Global Power" },
      { label: "Leaderboards" },
      { label: "Historical Rankings" },
      { label: "Player Achievements" },
      { label: "Marketplace Infrastructure" },
      { label: "Digital Ownership" },
      { label: "Provenance" },
      { label: "Advanced Blockchain Integration" },
      { label: "Improved Transaction Efficiency" },
      { label: "Account Abstraction" },
      { label: "Sponsored Transactions Research" },
      { label: "Advanced Scalability" },
      { label: "Infrastructure Optimization" },
      { label: "Developer / Ecosystem Tools" }
    ]
  },
  {
    id: "phase-7",
    number: 7,
    title: "Public Launch",
    status: "planned",
    narrative: "The world opens.",
    description: "Echelon opens its living world to the wider player base.",
    icon: Rocket,
    countLabel: "ROADMAP TARGETS",
    note: "Features listed here are targeted for the public launch phase and are not guaranteed at launch.",
    milestones: [
      { label: "Public Access", highlight: true },
      { label: "Public World" },
      { label: "Full Player Onboarding" },
      { label: "Account Creation" },
      { label: "Secure Authentication" },
      { label: "Player Progression" },
      { label: "Territory Systems" },
      { label: "Economy" },
      { label: "Diplomacy" },
      { label: "Warfare" },
      { label: "Kingdoms" },
      { label: "Nations" },
      { label: "Persistent History" },
      { label: "Marketplace" },
      { label: "ECH Integration" },
      { label: "Community Systems" },
      { label: "Player Support" },
      { label: "Moderation" },
      { label: "Anti-Cheat" },
      { label: "Security Monitoring" },
      { label: "Infrastructure Scaling" },
      { label: "Performance Optimization" },
      { label: "Analytics" },
      { label: "Global Events" },
      { label: "Seasonal Content" },
      { label: "Live Operations" },
      { label: "Bug Fixes" },
      { label: "Balance Updates" },
      { label: "Continuous Development" }
    ]
  },
  {
    id: "phase-8",
    number: 8,
    title: "Mobile",
    status: "planned",
    narrative: "The world becomes mobile.",
    description:
      "Bring Echelon's living world beyond the desktop and into the hands of players.",
    icon: Smartphone,
    countLabel: "ROADMAP TARGETS",
    platforms: ["Android", "iOS"],
    note: "No release date is set. Mobile applications are not yet available or approved on any app store.",
    milestones: [
      { label: "Android Application" },
      { label: "iOS Application" },
      { label: "Mobile Authentication" },
      { label: "Mobile Account Management" },
      { label: "Mobile World Map" },
      { label: "Mobile Territory Management" },
      { label: "Mobile Economy" },
      { label: "Mobile Diplomacy" },
      { label: "Mobile Notifications" },
      { label: "Mobile Player Communication" },
      { label: "Mobile Marketplace" },
      { label: "Mobile Progression" },
      { label: "Mobile Strategy Interface" },
      { label: "Mobile Performance Optimization" },
      { label: "Touch Controls" },
      { label: "Responsive Strategy UI" },
      { label: "Cross-Platform Accounts" },
      { label: "Cross-Platform Progression" },
      { label: "Cross-Platform World State" },
      { label: "Push Notifications" },
      { label: "Mobile Security" },
      { label: "App Store Preparation" },
      { label: "Google Play Preparation" },
      { label: "iOS App Store Preparation" },
      { label: "Mobile Analytics" },
      { label: "Mobile Live Updates" }
    ]
  },
  {
    id: "phase-9",
    number: 9,
    title: "Beyond the Roadmap",
    status: "coming-soon",
    narrative: "The world continues evolving.",
    description:
      "Echelon does not end with the initial roadmap. The world will continue to evolve through future systems, expansions, discoveries, and player-driven possibilities.",
    icon: InfinityIcon,
    countLabel: "EXPANSION CATEGORIES",
    milestoneVariant: "category",
    closingMessage: "THE ROADMAP ENDS. THE WORLD DOESN'T.",
    milestones: [
      { label: "New Worlds" },
      { label: "New Game Systems" },
      { label: "New Political Mechanics" },
      { label: "New Economic Systems" },
      { label: "New Strategic Mechanics" },
      { label: "New Content" },
      { label: "New Events" },
      { label: "New Platforms" },
      { label: "Community-Driven Features" },
      { label: "Ecosystem Expansion" },
      { label: "Performance Evolution" },
      { label: "Infrastructure Evolution" },
      { label: "Experimental Systems" },
      { label: "Player-Driven Possibilities" }
    ]
  }
];

export const currentRoadmapPhase: RoadmapPhase =
  roadmapPhases.find((phase) => phase.status === "current") ??
  roadmapPhases[0];

/** Highest phase number among the initial (non "coming-soon") phases. */
export const initialPhaseCount: number = roadmapPhases
  .filter((phase) => phase.status !== "coming-soon")
  .reduce((max, phase) => Math.max(max, phase.number), 0);
